apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
  namespace: default
data:
  index.html: |
    <html>
    <head><title>FluxCD App on OKE</title></head>
    <body>
      <h1>Hello from FluxCD + NGINX on Oracle OKE</h1>
    </body>
    </html>