apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: docker.io/nginx:1.25
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-html
              mountPath: /usr/share/nginx/html
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
            - name: nginx-auth
              mountPath: /etc/nginx/.htpasswd
              subPath: auth
      volumes:
        - name: nginx-html
          configMap:
            name: nginx-index
        - name: nginx-conf
          configMap:
            name: nginx-conf
        - name: nginx-auth
          secret:
            secretName: nginx-basic-auth
